[package]
name = "logic_tracer"
version = "0.0.2"
description = "Recognize a logic proposition and trace its truth value, also generate a truth table (still in development)"
license = "MIT"
repository = "https://github.com/Yrrrrrf/logic_tracer"
authors = ["Yrrrrrf"]
edition = "2021"

exclude = [
    ".vscode*",  # editor config
    "resources/data/*",  # data files (csv, json, etc)
    "target",  # build directory (compiled code)
    ".gitignore",  # ignore gitignore file
    "Cargo.lock",  # lock file (dependency versions)
    ]  # exclude these files from the package

# COMPILE OPTIMIZATION ------------------------------------------------------------------------
# where 1 is the lowest and 3 is the highest level of optimization

[profile.dev]
opt-level = 0  # no optimizations (fastest compile time, slowest runtime)

[profile.release]
opt-level = 3  # full optimizations (slowest compile time, fastest runtime)

# DEPENDENCIES --------------------------------------------------------------------------------

[dependencies]
log = "0.4.*"  # Logging (https://docs.rs/log/latest/log/)
dev_utils = "0.0.*"  # Development utilities (https://docs.rs/dev_utils/latest/dev_utils/)
# dev_utils = { path = "./../dev_utils" }

# ^ These is a temporal dependency, it will be removed in the future
regex = "1.*"  # Regular expressions (https://docs.rs/regex/latest/regex/)
