[package]
name = "logic_tracer"
version = "0.1.0"
description = "Recognize a logic proposition and trace its truth value, also generate a truth table (still in development)"
license = "MIT"
repository = "https://github.com/Yrrrrrf/logic_tracer"
authors = ["Yrrrrrf"]
edition = "2021"


exclude = [
    "resources/*",
    "target",
    ".gitignore",
    "Cargo.lock",
    "LICENSE",
    "README.md",

    # SOME POSSIBLE EXCLUDES (not sure if they are necessary)
    "tests",
    "benches", 
    "examples", 
    "docs"
    ]  # exclude these files from the package


# RUN MODE ------------------------------------------------------------------------------------

# [[bin]]  # add main.rs to the bin section
# name = "main"  # cargo run --bin main
# path = "src/main.rs"

# # add dev.rs to the bin section
# [[bin]]
# name = "dev"  # cargo run --bin dev
# path = "src/dev.rs"


# COMPILE OPTIMIZATION ------------------------------------------------------------------------
# where 1 is the lowest and 3 is the highest level of optimization

[profile.dev]
opt-level = 0  # no optimizations (fastest compile time, slowest runtime)

[profile.release]
opt-level = 3  # full optimizations (slowest compile time, fastest runtime)


# DEPENDENCIES --------------------------------------------------------------------------------

[dependencies]
# regex = { version = "1.9.1", features = ["unicode"] }  # Regular expressions (https://docs.rs/regex/1.4.5/regex/)
# reqwest = { version = "0.11", features = ["blocking", "json"] }  # HTTP client (https://docs.rs/reqwest/latest/reqwest/)
# tokio = { version = "1", features = ["full"] }  # Async runtime (https://docs.rs/tokio/1.0.0/tokio/)
# serde = { version = "1.0.164", features = ["derive"] }  # Serialization (https://docs.rs/serde/latest/serde/)

# clap = "3"  # Command line arguments (https://docs.rs/clap/3.0.0-beta.2/clap/)
colorful = {version = "0.2.2"}  # Colorful terminal output (https://docs.rs/colorful/latest/colorful/)

