[package]
name = "logic_tracer"
version = "0.0.1"
description = "Recognize a logic proposition and trace its truth value, also generate a truth table (still in development)"
license = "MIT"
repository = "https://github.com/Yrrrrrf/logic_tracer"
authors = ["Yrrrrrf"]
edition = "2021"

exclude = [
    ".vscode*",
    "examples/*",
    "resources/*",
    "target",
    ".gitignore",
    "Cargo.lock",
    "LICENSE",
    "README.md",
    ]  # exclude these files from the package

# COMPILE OPTIMIZATION ------------------------------------------------------------------------
# where 1 is the lowest and 3 is the highest level of optimization

[profile.dev]
opt-level = 0  # no optimizations (fastest compile time, slowest runtime)

[profile.release]
opt-level = 3  # full optimizations (slowest compile time, fastest runtime)

# DEPENDENCIES --------------------------------------------------------------------------------

[dependencies]

# todo: uncomment the SERDE and CLAP dependencies if you want to use the serialization and command line arguments features
# SERDE: serialize and deserialize data structures (https://docs.rs/serde/latest/serde/)
# CLAP: command line arguments (https://docs.rs/clap/latest/clap/)  // todo: add clap to the features list of the serde dependency
# serde = { version = "*", features = ["derive"] }  # Serialization (https://docs.rs/serde/latest/serde/)
# clap = {version = "*", features = ["color"]}  # Command line arguments (https://docs.rs/clap/latest/clap/)


# colorful = {version = "*"}  # Colorful terminal output (https://docs.rs/colorful/latest/colorful/)




# regex = { version = "*", features = ["unicode"] }  # Regular expressions (https://docs.rs/regex/1.4.5/regex/)

# reqwest = { version = "*", features = ["blocking", "json"] }  # HTTP client (https://docs.rs/reqwest/latest/reqwest/)
# tokio = { version = "*", features = ["full"] }  # Async runtime (https://docs.rs/tokio/1.0.0/tokio/)
