[package]
name = "logic_tracer"
version = "0.1.0"
edition = "2021"
authors = ["Yrrrrrf"]

license = "MIT"
description = "Recognize a logic proposition and trace its truth value, also generate a truth table (still in development)"
# repository = "
exclude = [
    "tests",
    "benches", 
    "examples", 
    "docs", 
    ".github", 
    ".gitignore", 
    ".gitattributes", 
    "Cargo.lock", 
    "README.md", 
    "LICENSE"
    ]  # exclude these files from the package


[profile.dev]
opt-level = 0  # no optimizations

[profile.release]
opt-level = 3  # full optimizations


# [[bin]]  # add main.rs to the bin section
# name = "main"  # cargo run --bin main
# path = "src/main.rs"

# # add dev.rs to the bin section
# [[bin]]
# name = "dev"  # cargo run --bin dev
# path = "src/dev.rs"


[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }  # HTTP client (https://docs.rs/reqwest/latest/reqwest/)
tokio = { version = "1", features = ["full"] }  # Async runtime (https://docs.rs/tokio/1.0.0/tokio/)
# serde = { version = "1.0.0", features = ["derive"] }  # Serialization (https://docs.serde.rs/serde/)

