[package]
name = "logic_tracer"
version = "0.0.13"
edition = {workspace = true }
repository = "https://github.com/Yrrrrrf/logic_tracer"
description = "Recognize a logic proposition and trace its truth value, also generate a truth table (still in development)"
authors = {workspace = true}
license = {workspace = true}
readme = "../../README.md"
keywords = ["logic", "proposition", "truth_table", "calculator", "compiler"]
categories = ["development-tools", "compilers", "data-structures"]

[dependencies]
log = "0.4.28"  # Logging (https://docs.rs/log/latest/log/)
dev_utils = "0.1.4"  # Development utilities (https://docs.rs/dev_utils/latest/dev_utils/)

# digital = "0.0.*"  # add latest
digital = { version = "0.0.1", path = "../digital" }

# proposition = "0.0.*"
proposition = { version = "0.0.1", path = "../proposition" }

# [dev-dependencies]
# pest = "*"  # Parser (https://docs.rs/pest/latest/pest/)
# regex = "*"  # Regular expressions (https://docs.rs/regex/latest/regex/)

[features]
default = []  # no features enabled by default

# Features are a way to enable or disable parts of your library
# combinational = []  # combinational logic stuff (gates, multiplexers, decoders, etc)
# sequential = []  # sequential logic stuff (flip-flops, registers, counters, etc)
digital = [
    # "combinational",
    # "sequential",
]  # digital logic stuff (combinational + sequential)

full = [

]  # all features enabled
